name: rbuild
description: Radxa Image Builder
inputs:
  board:
    required: true
  distro:
    required: true
  flavor:
    required: false
  artifacts:
    required: false
    default: 'false'
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: radxa-repo/rbuild
    - name: Build
      shell: bash
      run: |
        sudo apt install -y debos
    - name: Build
      shell: bash
      run: |
        mkdir .output
        cd .output
        sudo ../rbuild --compress --native-debos -s --root ${{ inputs.board }} ${{ inputs.distro }} ${{ inputs.flavor }}
        if [ -n "$(ls -A ./* 2>/dev/null)" ]
        then
          sudo chown $USER ./*
        fi
    - name: Upload image artifacts
      if: inputs.artifacts == 'true' && inputs.boards != 'rootfs'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.boards }}_${{ matrix.distros }}_${{ matrix.flavors }}
        path: .output
    - name: Upload rootfs artifacts
      if: inputs.artifacts == 'true' && inputs.boards == 'rootfs'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.boards }}_${{ matrix.distros }}_${{ matrix.flavors }}
        path: .rootfs
    - name: Upload image
      if: inputs.release-id != '' && inputs.github-token != '' && inputs.board != 'rootfs'
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: .output/*
        draft: false
    - name: Upload rootfs
      if: inputs.release-id != '' && inputs.github-token != '' && inputs.board == 'rootfs'
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: .rootfs/*
        draft: false
    - name: Rollback release
      if: failure() && inputs.release-id != '' && inputs.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}