name: rbuild
description: Radxa Image Builder
inputs:
  board:
    required: true
  distro:
    required: true
  flavor:
    required: false
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: radxa-repo/rbuild
    - name: Build
      shell: bash
      run: |
        mkdir .output
        cd .output
        ../rbuild -s ${{ inputs.board }} ${{ inputs.distro }} ${{ inputs.flavor }}
    - name: Upload
      if: inputs.release-id != '' && inputs.github-token != ''
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: .output/*
        draft: false
    - name: Rollback release
      if: failure() && inputs.release-id != '' && inputs.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}