[book]
authors = ["Radxa Limited"]
language = "en"
multilingual = true
src = "docs"
title = "rbuild"

[output.html]
git-repository-url = "https://github.com/radxa-repo/rbuild/tree/main"
edit-url-template = "https://github.com/radxa-repo/rbuild/edit/main/{path}"