{{- $distro := .distro -}}

{{- $architecture := .architecture -}}

architecture: {{ $architecture }}

actions:
  - action: apt
    description: Install common desktop packages
    packages:
      - xdg-utils
      - smplayer
  {{ if eq $distro "debian"}}
      - firefox-esr
  {{ else if eq $distro "ubuntu"}}
      - firefox
  {{ end }}