{{- $distro := .distro -}}
{{- $suite := .suite -}}

{{- $architecture := .architecture -}}

architecture: {{ $architecture }}

actions:
  - action: apt
    description: Install sway packages
    packages:
      - foot
      - greetd
      - suckless-tools
      - sway
      - sway-backgrounds
      - swaybg
      - swayidle
      - swaylock
      - xdg-desktop-portal-wlr
      - xwayland

  - action: recipe
    description: Install common desktop packages
    recipe: .desktop.yaml
    variables:
      distro: {{ $distro }}
      suite: {{ $suite }}
